export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  console.log("Montando layout principal");
  return (
      <html lang="en">
          <body>
              <div>
                  <nav>
                      <h2>Menu Principal</h2>
                      <ul>
                          <li>
                              <a href="/">Home</a>
                          </li>
                          <li>
                              <a href="/novarota">Nova Rota</a>
                          </li>
                      </ul>
                  </nav>
              </div>
              <main>{children}</main>
          </body>
      </html>
  );
}


